export { AutoICD } from "./client.js";

export type {
  AutoICDOptions,
  CodeOptions,
  CodeMatch,
  CodingEntity,
  CodingResponse,
  SearchOptions,
  CodeDetail,
  CodeDetailFull,
  ChapterInfo,
  CodeSearchResponse,
  PIIEntity,
  AnonymizeResponse,
  RateLimit,
  ICD11CodeDetail,
  ICD11ChapterInfo,
  CrosswalkMapping,
  ICD11CodeDetailFull,
  ICD11CodeSearchResult,
  ICD11CodeSearchResponse,
  ICFComponent,
  ICFCodeSummary,
  ICFCodeDetail,
  ICFCodeResult,
  ICFCodingEntity,
  ICFCodingResponse,
  ICFSearchResponse,
  ICFCoreSetResult,
  ICFCrossReference,
  LOINCCodeSummary,
  LOINCCodeDetail,
  LOINCSearchResponse,
  LOINCCodeResult,
  LOINCCodingEntity,
  LOINCCodingResponse,
  AuditCapability,
  AuditCode,
  AuditDocument,
  AuditContext,
  AuditRequest,
  AuditResponse,
  EvidenceSpan,
  ConfirmedCode,
  MissedCode,
  UnsupportedCode,
  SpecificityUpgrade,
  DenialRisk,
  ProblemListEntry,
  AuditTotals,
  RatesUsed,
  UpgradeHint,
} from "./types.js";

export {
  AutoICDError,
  AuthenticationError,
  RateLimitError,
  NotFoundError,
} from "./errors.js";
